spring:
  profiles:
    active: development
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        cache: TRACE
---
spring:
  profiles: development
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/axaempsvcdb;DB_CLOSE_ON_EXIT=FALSE
---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: H2
  datasource:
    url: jdbc:h2:mem:axaempsvctestdb;DB_CLOSE_ON_EXIT=FALSE
