spring:
  h2:
    console:
      enabled: true
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:~/axaempsvcdb
---
spring:
  profiles: test
  jpa:
    show_sql: true
    database: H2
  datasource:
    url: jdbc:h2:mem:axaempsvctestdb;DB_CLOSE_ON_EXIT=FALSE
